# Generated by Django 3.1.4 on 2021-05-03 18:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/ClientProfilePic/')),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/GuestProfilePic/')),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationGuest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 5, 4, 0, 6, 5, 884711))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2021, 5, 4, 0, 6, 5, 884711))),
                ('guest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.guest')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationClient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 5, 4, 0, 6, 5, 885708))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2021, 5, 4, 0, 6, 5, 885708))),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.client')),
            ],
        ),
        migrations.CreateModel(
            name='FeedBackGuest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback', models.TextField()),
                ('feedback_reply', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 5, 4, 0, 6, 5, 884711))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2021, 5, 4, 0, 6, 5, 884711))),
                ('guest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.guest')),
            ],
        ),
        migrations.CreateModel(
            name='FeedBackClient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback', models.TextField()),
                ('feedback_reply', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 5, 4, 0, 6, 5, 884711))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2021, 5, 4, 0, 6, 5, 884711))),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.client')),
            ],
        ),
    ]
